version: "3.9"

services:

  db-agendamento-service:
    image: mysql:8.0
    container_name: db-agendamento-service
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: agendamento_service_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - agendamento_service_data:/var/lib/mysql

  db-clinica-service:
    image: mysql:8.0
    container_name: db-clinica-service
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: clinica_service_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - clinica_service_data:/var/lib/mysql

  db-centro-laboratorio:
    image: mysql:8.0
    container_name: db-centro-laboratorio
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: centro_laboratorio_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - centro_laboratorio_data:/var/lib/mysql

volumes:
  agendamento_service_data:
  clinica_service_data:
  centro_laboratorio_data: